# Run with: cmake -P tests/config/test_resolver.cmake
set(root "${CMAKE_CURRENT_LIST_DIR}/../..")
include("${root}/config/aclass_config.cmake")

if(DEFINED CASE)
    if(CASE STREQUAL "missing_dma")
        set(ADRV_MODULE_DMA_REQUESTED OFF)
    elseif(CASE STREQUAL "missing_device_dma")
        set(ADEV_USART_DMA_REQUESTED OFF)
    elseif(CASE STREQUAL "missing_device")
        set(ADEV_USART_REQUESTED OFF)
    elseif(CASE STREQUAL "missing_gpio")
        set(ADRV_MODULE_GPIO_REQUESTED OFF)
    elseif(CASE STREQUAL "invalid_bool")
        set(ADEV_USART_ASYNC_REQUESTED typo)
    elseif(CASE STREQUAL "independent_app")
        # Shell may use a non-USART transport; the generic resolver must allow it.
        set(ADEV_LED_REQUESTED OFF)
        set(ADEV_USART_REQUESTED OFF)
        foreach(feature INTERRUPT DMA ASYNC RS485)
            set(ADEV_USART_${feature}_REQUESTED OFF)
        endforeach()
    elseif(CASE STREQUAL "missing_input")
        unset(ADRV_MODULE_DMA_REQUESTED)
    elseif(CASE STREQUAL "minimal" OR CASE STREQUAL "polling")
        set(ASHELL_REQUESTED OFF)
        foreach(feature INTERRUPT DMA ASYNC RS485)
            set(ADEV_USART_${feature}_REQUESTED OFF)
        endforeach()
        set(ADRV_USART_INTERRUPT_REQUESTED OFF)
        set(ADRV_USART_ASYNC_REQUESTED OFF)
        set(ADRV_MODULE_DMA_REQUESTED OFF)
        if(CASE STREQUAL "minimal")
            set(ADEV_USART_REQUESTED OFF)
            set(ADRV_MODULE_USART_REQUESTED OFF)
            set(ADRV_USART_INTERRUPT_REQUESTED OFF)
            set(ADRV_USART_ASYNC_REQUESTED OFF)
            set(ADRV_MODULE_DMA_REQUESTED OFF)
        endif()
    endif()
    include("${root}/cmake/aclass_resolve.cmake")
    if(CASE STREQUAL "minimal" AND ADRV_MODULE_DMA)
        message(FATAL_ERROR "Unexpected DMA enable")
    endif()
    return()
endif()

foreach(case default minimal polling independent_app missing_input missing_dma
        missing_device_dma missing_device missing_gpio invalid_bool)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error
    )
    if(case MATCHES "^(default|minimal|polling|independent_app)$")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${case} should succeed: ${error}")
        endif()
    else()
        if(result EQUAL 0)
            message(FATAL_ERROR "${case} should fail")
        endif()
        if(case STREQUAL "missing_input")
            set(expected "Missing configuration input: ADRV_MODULE_DMA_REQUESTED")
        elseif(case STREQUAL "missing_dma")
            set(expected "ADRV_MODULE_DMA_REQUESTED")
        elseif(case STREQUAL "missing_device_dma")
            set(expected "ADEV_USART_DMA_REQUESTED")
        elseif(case STREQUAL "missing_device")
            set(expected "ADEV_USART_REQUESTED")
        elseif(case STREQUAL "missing_gpio")
            set(expected "ADRV_MODULE_GPIO_REQUESTED")
        else()
            set(expected "must be boolean")
        endif()
        if(NOT error MATCHES "${expected}")
            message(FATAL_ERROR "${case} returned wrong diagnostic: ${error}")
        endif()
    endif()
endforeach()
message(STATUS "Configuration positive/negative cases passed")
