# Run with: cmake -P tests/config/test_resolver.cmake
set(root "${CMAKE_CURRENT_LIST_DIR}/../..")
include("${root}/config/aclass_config.cmake")
# Use a full-capability fixture independently of the minimal product profile.
foreach(feature INTERRUPT DIRECT ASYNC RS485)
    set(ADEV_USART_${feature}_ENABLE ON)
endforeach()
set(ADRV_USART_DMA_ENABLE ON)
set(ADRV_MODULE_DMA_ENABLE ON)

if(DEFINED CASE)
    if(CASE STREQUAL "led_static")
        set(ADEV_LED_DYNAMIC_ENABLE OFF)
    elseif(CASE STREQUAL "led_dynamic")
        set(ADEV_LED_STATIC_ENABLE OFF)
        set(ADEV_LED_DYNAMIC_ENABLE ON)
    elseif(CASE STREQUAL "led_both")
        set(ADEV_LED_DYNAMIC_ENABLE ON)
    elseif(CASE STREQUAL "led_no_allocation")
        set(ADEV_LED_STATIC_ENABLE OFF)
        set(ADEV_LED_DYNAMIC_ENABLE OFF)
    elseif(CASE STREQUAL "led_invalid_bool")
        set(ADEV_LED_STATIC_ENABLE typo)
    elseif(CASE STREQUAL "bus_static")
        set(ABUS_DYNAMIC_ENABLE OFF)
    elseif(CASE STREQUAL "bus_dynamic")
        set(ABUS_STATIC_ENABLE OFF)
    elseif(CASE STREQUAL "log_off")
        set(ALOG_ENABLE OFF)
    elseif(CASE STREQUAL "log_invalid_level")
        set(ALOG_OUTPUT_LEVEL 6)
    elseif(CASE STREQUAL "log_small_buffer")
        set(ALOG_LINE_BUFFER_SIZE 128)
    elseif(CASE STREQUAL "log_large_buffer")
        set(ALOG_LINE_BUFFER_SIZE 8192)
    elseif(CASE STREQUAL "log_invalid_bool")
        set(ALOG_ENABLE typo)
    elseif(CASE STREQUAL "log_independent")
        set(ASHELL_ENABLE OFF)
        set(ADATABASE_ENABLE OFF)
        set(ADEV_FLASH25Q_ENABLE OFF)
    elseif(CASE STREQUAL "bus_no_allocation")
        set(ABUS_STATIC_ENABLE OFF)
        set(ABUS_DYNAMIC_ENABLE OFF)
    elseif(CASE STREQUAL "bus_check_off")
        set(ABUS_DEF_CHECK_ENABLE OFF)
    elseif(CASE STREQUAL "bus_check_invalid")
        set(ABUS_DEF_CHECK_ENABLE typo)
    elseif(CASE STREQUAL "bus_none")
        set(ABUS_LOCK_GRANULARITY NONE)
    elseif(CASE STREQUAL "bus_sig")
        set(ABUS_LOCK_GRANULARITY SIG)
    elseif(CASE STREQUAL "bus_off")
        set(ABUS_ENABLE OFF)
        set(AMODBUS_ENABLE OFF)
    elseif(CASE STREQUAL "modbus_missing_bus")
        set(AMODBUS_ENABLE ON)
        set(ABUS_ENABLE OFF)
    elseif(CASE STREQUAL "modbus_no_allocation")
        set(AMODBUS_STATIC_ENABLE OFF)
        set(AMODBUS_DYNAMIC_ENABLE OFF)
    elseif(CASE STREQUAL "modbus_no_role")
        set(AMODBUS_CLIENT_ENABLE OFF)
        set(AMODBUS_SERVER_ENABLE OFF)
    elseif(CASE STREQUAL "modbus_invalid_bool")
        set(AMODBUS_CLIENT_ENABLE typo)
    elseif(CASE STREQUAL "modbus_client_static")
        set(AMODBUS_SERVER_ENABLE OFF)
        set(AMODBUS_DYNAMIC_ENABLE OFF)
    elseif(CASE STREQUAL "modbus_server_dynamic")
        set(AMODBUS_CLIENT_ENABLE OFF)
        set(AMODBUS_STATIC_ENABLE OFF)
    elseif(CASE STREQUAL "bus_invalid_lock")
        set(ABUS_LOCK_GRANULARITY typo)
    elseif(CASE STREQUAL "missing_dma")
        set(ADRV_MODULE_DMA_ENABLE OFF)
    elseif(CASE STREQUAL "missing_usart_dma")
        set(ADRV_USART_DMA_ENABLE OFF)
    elseif(CASE STREQUAL "dma_without_async")
        set(ADEV_USART_ASYNC_ENABLE OFF)
    elseif(CASE STREQUAL "async_without_direct")
        set(ADEV_USART_DIRECT_ENABLE OFF)
    elseif(CASE STREQUAL "direct_without_dma")
        set(ADEV_USART_INTERRUPT_ENABLE OFF)
        set(ADEV_USART_ASYNC_ENABLE OFF)
        set(ADEV_USART_RS485_ENABLE OFF)
        set(ADRV_USART_INTERRUPT_ENABLE OFF)
        set(ADRV_USART_DMA_ENABLE OFF)
        set(ADRV_MODULE_DMA_ENABLE OFF)
    elseif(CASE STREQUAL "missing_device")
        set(ADEV_USART_ENABLE OFF)
    elseif(CASE STREQUAL "missing_gpio")
        set(ADRV_MODULE_GPIO_ENABLE OFF)
    elseif(CASE STREQUAL "invalid_bool")
        set(ADEV_USART_ASYNC_ENABLE typo)
    elseif(CASE STREQUAL "independent_app")
        # Shell may use a non-USART transport; the generic resolver must allow it.
        set(ADEV_LED_ENABLE OFF)
        set(ADEV_USART_ENABLE OFF)
        set(ADEV_USART_STATIC_ENABLE OFF)
        set(ADEV_USART_DYNAMIC_ENABLE OFF)
        foreach(feature INTERRUPT DIRECT ASYNC RS485)
            set(ADEV_USART_${feature}_ENABLE OFF)
        endforeach()
    elseif(CASE STREQUAL "missing_input")
        unset(ADRV_MODULE_DMA_ENABLE)
    elseif(CASE STREQUAL "database_custom")
        set(ADATABASE_ENABLE ON)
        set(ADEV_FLASH25Q_ENABLE OFF)
    elseif(CASE STREQUAL "database_missing_memory")
        set(AMEMORY_ENABLE OFF)
    elseif(CASE STREQUAL "memory_invalid_capacity")
        set(AMEMORY_MAX_PARTITIONS 0)
    elseif(CASE STREQUAL "memory_invalid_bool")
        set(AMEMORY_ENABLE typo)
    elseif(CASE STREQUAL "memory_off")
        set(ADATABASE_ENABLE OFF)
        set(AMEMORY_ENABLE OFF)
    elseif(CASE STREQUAL "minimal" OR CASE STREQUAL "polling")
        set(ASHELL_ENABLE OFF)
        foreach(feature INTERRUPT DIRECT ASYNC RS485)
            set(ADEV_USART_${feature}_ENABLE OFF)
        endforeach()
        set(ADRV_USART_INTERRUPT_ENABLE OFF)
        set(ADRV_USART_DMA_ENABLE OFF)
        set(ADRV_MODULE_DMA_ENABLE OFF)
        if(CASE STREQUAL "minimal")
            set(ADEV_USART_ENABLE OFF)
            set(ADEV_USART_STATIC_ENABLE OFF)
            set(ADEV_USART_DYNAMIC_ENABLE OFF)
            set(ADRV_MODULE_USART_ENABLE OFF)
            set(ADRV_USART_INTERRUPT_ENABLE OFF)
            set(ADRV_USART_DMA_ENABLE OFF)
            set(ADRV_MODULE_DMA_ENABLE OFF)
        endif()
    endif()
    include("${root}/cmake/aclass_resolve.cmake")
    if(CASE STREQUAL "dma_without_async")
        if(NOT ADRV_USART_DMA_ENABLE OR NOT ADEV_USART_DIRECT_ENABLE
                OR ADEV_USART_ASYNC_ENABLE)
            message(FATAL_ERROR "Driver DMA and device Direct must remain independent of async APIs")
        endif()
    endif()
    if(CASE STREQUAL "minimal" AND ADRV_MODULE_DMA_ENABLE)
        message(FATAL_ERROR "Unexpected DMA enable")
    endif()
    return()
endif()

foreach(case default bus_static bus_dynamic bus_no_allocation bus_check_off bus_check_invalid bus_none bus_sig bus_off bus_invalid_lock
        led_static led_dynamic led_both led_no_allocation led_invalid_bool
        log_off log_invalid_level log_small_buffer log_large_buffer
        log_invalid_bool log_independent
        minimal polling independent_app missing_input missing_dma
        missing_usart_dma dma_without_async
        async_without_direct direct_without_dma missing_device missing_gpio invalid_bool
        database_custom database_missing_memory memory_invalid_capacity
        memory_invalid_bool memory_off
        modbus_missing_bus modbus_no_allocation modbus_no_role
        modbus_invalid_bool modbus_client_static modbus_server_dynamic)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error
    )
    if(case MATCHES "^led_(static|dynamic|both)$" OR
       case MATCHES "^(default|bus_static|bus_dynamic|bus_check_off|bus_none|bus_sig|bus_off|minimal|polling|independent_app|database_custom|memory_off|dma_without_async|async_without_direct|direct_without_dma|log_off|log_independent|modbus_client_static|modbus_server_dynamic)$")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${case} should succeed: ${error}")
        endif()
    else()
        if(result EQUAL 0)
            message(FATAL_ERROR "${case} should fail")
        endif()
        if(case STREQUAL "led_no_allocation")
            set(expected "LED requires STATIC or DYNAMIC")
        elseif(case STREQUAL "bus_no_allocation")
            set(expected "aBus requires STATIC or DYNAMIC")
        elseif(case STREQUAL "modbus_missing_bus")
            set(expected "ABUS_ENABLE")
        elseif(case STREQUAL "modbus_no_allocation")
            set(expected "aModbus requires STATIC or DYNAMIC")
        elseif(case STREQUAL "modbus_no_role")
            set(expected "aModbus requires CLIENT or SERVER")
        elseif(case STREQUAL "log_invalid_level")
            set(expected "ALOG_OUTPUT_LEVEL")
        elseif(case MATCHES "^log_(small|large)_buffer$")
            set(expected "ALOG_LINE_BUFFER_SIZE")
        elseif(case STREQUAL "bus_invalid_lock")
            set(expected "ABUS_LOCK_GRANULARITY")
        elseif(case STREQUAL "missing_input")
            set(expected "Missing configuration input: ADRV_MODULE_DMA_ENABLE")
        elseif(case STREQUAL "missing_dma")
            set(expected "ADRV_MODULE_DMA_ENABLE")
        elseif(case STREQUAL "missing_usart_dma")
            set(expected "ADRV_USART_DMA_ENABLE")
        elseif(case STREQUAL "missing_device")
            set(expected "ADEV_USART_ENABLE")
        elseif(case STREQUAL "missing_gpio")
            set(expected "ADRV_MODULE_GPIO_ENABLE")
        elseif(case STREQUAL "database_missing_memory")
            set(expected "AMEMORY_ENABLE")
        elseif(case STREQUAL "memory_invalid_capacity")
            set(expected "AMEMORY_MAX_PARTITIONS")
        else()
            set(expected "must be boolean")
        endif()
        if(NOT error MATCHES "${expected}")
            message(FATAL_ERROR "${case} returned wrong diagnostic: ${error}")
        endif()
    endif()
endforeach()
message(STATUS "Configuration positive/negative cases passed")
