#ifndef ADATABASE_FLASH_LAYOUT_H
#define ADATABASE_FLASH_LAYOUT_H

/* Product-specific storage layout used by the FlashDB FAL adapter. */
#define ADATABASE_FLASH_DEVICE_NAME "flash25"
#define ADATABASE_FLASH_BLOCK_SIZE 4096U
#define ADATABASE_FLASH_OPERATION_TIMEOUT_MS 5000U
#define ADATABASE_FLASH_CAPACITY_BYTES (16U * 1024U * 1024U)

#define ADATABASE_PART_PARAM_NAME "param"
#define ADATABASE_PART_PARAM_OFFSET 0x00100000U
#define ADATABASE_PART_PARAM_SIZE   0x00020000U

#define ADATABASE_PART_LOG_NAME "log"
#define ADATABASE_PART_LOG_OFFSET 0x00120000U
#define ADATABASE_PART_LOG_SIZE   0x00080000U

#endif
