# FreeRTOS product overrides for this firmware.
# Reusable defaults and the FreeRTOSConfig.h template are owned by aOS.

set(FREERTOS_CPU_CLOCK_HZ ${MCU_CORE_CLOCK_HZ})
set(FREERTOS_TICK_RATE_HZ 1000)
set(FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES 2)

set(FREERTOS_MAX_PRIORITIES 8)
set(FREERTOS_MINIMAL_STACK_SIZE 128)
set(FREERTOS_TOTAL_HEAP_SIZE 24576)
set(FREERTOS_MAX_TASK_NAME_LEN 16)

set(FREERTOS_USE_MALLOC_FAILED_HOOK 1)
set(FREERTOS_CHECK_FOR_STACK_OVERFLOW 2)

set(FREERTOS_USE_TIMERS 1)
set(FREERTOS_TIMER_TASK_PRIORITY 6)
set(FREERTOS_TIMER_QUEUE_LENGTH 8)
set(FREERTOS_TIMER_TASK_STACK_DEPTH 256)

set(FREERTOS_HEAP_IMPLEMENTATION 4)
