# FreeRTOS reusable defaults owned by aOS.
# Project policy overrides belong in config/freeRTOS_config.cmake.

set(FREERTOS_CPU_CLOCK_HZ
    "${MCU_CORE_CLOCK_HZ}")
set(FREERTOS_SYSTICK_CLOCK_DIVISOR
    8)
set(FREERTOS_TICK_RATE_HZ
    1000)

set(FREERTOS_MAX_PRIORITIES
    8)
set(FREERTOS_MINIMAL_STACK_SIZE
    128)
set(FREERTOS_TOTAL_HEAP_SIZE
    24576)
set(FREERTOS_MAX_TASK_NAME_LEN
    16)

set(FREERTOS_USE_16_BIT_TICKS
    0)
set(FREERTOS_USE_PREEMPTION
    1)
set(FREERTOS_USE_TIME_SLICING
    1)
set(FREERTOS_IDLE_SHOULD_YIELD
    1)
set(FREERTOS_USE_TICKLESS_IDLE
    0)
set(FREERTOS_USE_TASK_NOTIFICATIONS
    1)
set(FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES
    2)
set(FREERTOS_USE_TRACE_FACILITY
    0)
set(FREERTOS_USE_STATS_FORMATTING_FUNCTIONS
    0)
set(FREERTOS_USE_CO_ROUTINES
    0)
set(FREERTOS_USE_APPLICATION_TASK_TAG
    0)
set(FREERTOS_NUM_THREAD_LOCAL_STORAGE_POINTERS
    1)

set(FREERTOS_USE_IDLE_HOOK
    0)
set(FREERTOS_USE_TICK_HOOK
    0)
set(FREERTOS_USE_MALLOC_FAILED_HOOK
    1)
set(FREERTOS_CHECK_FOR_STACK_OVERFLOW
    2)

set(FREERTOS_USE_TIMERS
    1)
set(FREERTOS_TIMER_TASK_PRIORITY
    6)
set(FREERTOS_TIMER_QUEUE_LENGTH
    8)
set(FREERTOS_TIMER_TASK_STACK_DEPTH
    256)

set(FREERTOS_SUPPORT_DYNAMIC_ALLOCATION
    1)
set(FREERTOS_SUPPORT_STATIC_ALLOCATION
    0)
set(FREERTOS_APPLICATION_ALLOCATED_HEAP
    0)

set(FREERTOS_USE_COUNTING_SEMAPHORES
    1)
set(FREERTOS_USE_MUTEXES
    1)
set(FREERTOS_USE_RECURSIVE_MUTEXES
    1)
set(FREERTOS_USE_QUEUE_SETS
    1)
set(FREERTOS_QUEUE_REGISTRY_SIZE
    0)

set(FREERTOS_ENABLE_MPU
    0)
set(FREERTOS_ENABLE_FPU
    1)
set(FREERTOS_ENABLE_MVE
    0)
set(FREERTOS_ENABLE_TRUSTZONE
    0)
set(FREERTOS_RUN_FREERTOS_SECURE_ONLY
    1)

set(FREERTOS_PRIO_BITS
    4)
set(FREERTOS_LIBRARY_LOWEST_INTERRUPT_PRIORITY
    15)
set(FREERTOS_LIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY
    5)

set(FREERTOS_INCLUDE_vTaskPrioritySet
    1)
set(FREERTOS_INCLUDE_uxTaskPriorityGet
    1)
set(FREERTOS_INCLUDE_vTaskDelete
    1)
set(FREERTOS_INCLUDE_vTaskSuspend
    1)
set(FREERTOS_INCLUDE_xTaskDelayUntil
    1)
set(FREERTOS_INCLUDE_vTaskDelay
    1)
set(FREERTOS_INCLUDE_xTaskGetSchedulerState
    1)
set(FREERTOS_INCLUDE_xTaskGetCurrentTaskHandle
    1)
set(FREERTOS_INCLUDE_uxTaskGetStackHighWaterMark
    1)
set(FREERTOS_INCLUDE_xTaskGetIdleTaskHandle
    0)
set(FREERTOS_INCLUDE_eTaskGetState
    0)
set(FREERTOS_INCLUDE_xTimerPendFunctionCall
    1)
set(FREERTOS_INCLUDE_xSemaphoreGetMutexHolder
    1)
set(FREERTOS_INCLUDE_xTaskAbortDelay
    0)

set(FREERTOS_HEAP_IMPLEMENTATION
    4)
