# Reusable libraries only: the caller selects the toolchain and owns main().
include_guard(GLOBAL)
function(aclass_add_libraries)
    cmake_parse_arguments(LIB "" "CONFIG_FILE" "" ${ARGN})
    if(LIB_UNPARSED_ARGUMENTS OR NOT LIB_CONFIG_FILE)
        message(FATAL_ERROR "aclass_add_libraries requires CONFIG_FILE")
    endif()
    if(NOT TARGET aclass_project_options)
        message(FATAL_ERROR "Call aclass_initialize before aclass_add_libraries")
    endif()
    set(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/..")
    include("${LIB_CONFIG_FILE}")
    include("${root}/cmake/aclass_resolve.cmake")
    add_subdirectory("${root}/platform" "${CMAKE_CURRENT_BINARY_DIR}/aclass/platform")
    add_subdirectory("${root}/device" "${CMAKE_CURRENT_BINARY_DIR}/aclass/device")
    add_subdirectory("${root}/func" "${CMAKE_CURRENT_BINARY_DIR}/aclass/func")
    # Export resolved capability variables for the product application.
    get_cmake_property(variables VARIABLES)
    foreach(variable IN LISTS variables)
        if(variable MATCHES
           "^(ABUS_|AOS_|ASHELL_|ALOG_|ADATABASE_|AMODBUS_|ADEV_|ADRV_)")
            set(${variable} "${${variable}}" PARENT_SCOPE)
        endif()
    endforeach()
endfunction()
