#ifndef APP_SYSTEM_CONFIG_H
#define APP_SYSTEM_CONFIG_H

#include "aDev_led.h"
#include "aDrv_basic.h"

#if ASHELL_ENABLED
#include "aDev_usart.h"
#endif

#define ASYSTEM_STATUS_LED_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 8)
#define ASYSTEM_STATUS_LED_ACTIVE_LEVEL ADEV_LED_ACTIVE_LOW
#define ASYSTEM_STATUS_BLINK_PERIOD_MS 500U

#if ASHELL_ENABLED

#define ASYSTEM_SHELL_USART ADRV_USART_0
#define ASYSTEM_SHELL_TX_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 9)
#define ASYSTEM_SHELL_RX_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 10)
#define ASYSTEM_SHELL_BAUD_RATE 115200U
#define ASYSTEM_SHELL_IO_TIMEOUT A_TIMEOUT_MS(20U)

/* Shell: buffered interrupt TX + circular DMA RX + RX IDLE detection. */
#define ASYSTEM_SHELL_USART_MODE                    \
    (ADEV_USART_TX_INTERRUPT_BUFFERED |             \
     ADEV_USART_RX_DMA_CIRCULAR |                   \
     ADEV_USART_OPTION_RX_IDLE)
#define ASYSTEM_SHELL_IRQ_PRIORITY 6U
#define ASYSTEM_SHELL_RX_BUFFER_SIZE 256U
#define ASYSTEM_SHELL_TX_BUFFER_SIZE 256U

#endif

#endif
