#ifndef APP_SYSTEM_CONFIG_H
#define APP_SYSTEM_CONFIG_H

#include "aDev_led.h"
#include "aDrv_basic.h"

#if ASYSTEM_SHELL_ENABLED
#include "aDev_usart.h"
#endif

#define ASYSTEM_STATUS_LED_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 8)
#define ASYSTEM_STATUS_LED_ACTIVE_LEVEL ADEV_LED_ACTIVE_LOW
#define ASYSTEM_STATUS_BLINK_PERIOD_MS 500U

#if ASYSTEM_SHELL_ENABLED

#define ASYSTEM_SHELL_USART ADRV_USART_0
#define ASYSTEM_SHELL_TX_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 9)
#define ASYSTEM_SHELL_RX_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 10)
#define ASYSTEM_SHELL_BAUD_RATE 115200U
#define ASYSTEM_SHELL_IO_TIMEOUT A_TIMEOUT_MS(20U)

/*
 * ADEV_USART_MODE_POLLING:        polling TX and RX
 * ADEV_USART_MODE_DMA_TX:         DMA TX, polling RX
 * ADEV_USART_MODE_INTERRUPT_IDLE: interrupt TX/RX with IDLE detection
 * ADEV_USART_MODE_BUFFERED_TX_DMA_RX_IDLE:
 *                                  buffered interrupt TX, DMA RX + IDLE
 */
#define ASYSTEM_SHELL_USART_MODE ADEV_USART_MODE_BUFFERED_TX_DMA_RX_IDLE
#define ASYSTEM_SHELL_IRQ_PRIORITY 6U
#define ASYSTEM_SHELL_RX_BUFFER_SIZE 256U
#define ASYSTEM_SHELL_RX_DMA_BUFFER_SIZE 128U
#define ASYSTEM_SHELL_TX_BUFFER_SIZE 256U

#endif

#endif
