#ifndef APP_SYSTEM_CONFIG_H
#define APP_SYSTEM_CONFIG_H

#include "aDev_led.h"
#include "aDev_usart.h"
#include "aDrv_basic.h"

#define SYSTEM_STATUS_LED_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 8)
#define SYSTEM_STATUS_LED_ACTIVE_LEVEL ADEV_LED_ACTIVE_LOW
#define SYSTEM_STATUS_BLINK_PERIOD_MS 500U

#define SYSTEM_SHELL_USART ADRV_USART_0
#define SYSTEM_SHELL_TX_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 9)
#define SYSTEM_SHELL_RX_PIN ADRV_PIN(ADRV_GPIO_PORT_A, 10)
#define SYSTEM_SHELL_BAUD_RATE 115200U
#define SYSTEM_SHELL_IO_TIMEOUT A_TIMEOUT_MS(20U)

/*
 * ADEV_USART_MODE_POLLING:        polling TX and RX
 * ADEV_USART_MODE_DMA_TX:         DMA TX, polling RX
 * ADEV_USART_MODE_INTERRUPT_IDLE: interrupt TX/RX with IDLE detection
 */
#define SYSTEM_SHELL_USART_MODE ADEV_USART_MODE_INTERRUPT_IDLE
#define SYSTEM_SHELL_IRQ_PRIORITY 6U
#define SYSTEM_SHELL_RX_BUFFER_SIZE 256U
#define SYSTEM_SHELL_TX_BUFFER_SIZE 256U

#endif
